on: [push]
jobs:
  test:
    runs-on: docker
    steps:
      - name: Install Refresh Packages
        run: apt-get update

      - name: Install Buildah
        run: apt-get -y install buildah

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        id: build_image
        uses: https://github.com/redhat-actions/buildah-build@v2
        with:
          image: bluesky-cross-poster
          tags: latest
          containerfile: |
            ./Containerfile

      - name: Push
        id: push-to-registry
        uses: https://github.com/redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: git.hack13.dev
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
