on: [push]
jobs:
  test:
    runs-on: docker
    container:
      options: --privileged --user 1000
    steps:
      - name: Update Packages
        run: apt-get update -y

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          registry: git.hack13.dev
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: git.hack13.dev/bluesky-cross-poster:latest
