on: [push]
jobs:
  test:
    runs-on: docker
    container:
      options: --privileged
    steps:
      - name: Update Packages
        run: apt-get update -y

      - name: Build Image
        run: apt-get install -y buildah

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Image
        id: build
        uses: https://github.com/redhat-actions/buildah-build@v2
        with:
          image: bluesky-cross-poster
          tags: latest
          containerfiles: |
            ./Dockerfile

      - name: Push to Registry
        uses: https://github.com/redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build.outputs.image }}}
          tags: ${{ steps.build.outputs.tags }}
          registry: git.hack13.dev
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
